pipeline {
    agent any

    tools {
        maven 'Maven_3.8.6'
        jdk 'JDK_17'
    }

    environment {
        CATALINA_HOME = 'D:\\DevopsTaining\\All softwares\\apache-tomcat-9.0.104\\apache-tomcat-9.0.104'
    }

    stages {
        stage('Build WAR') {
            steps {
                dir('DeclarativeWebapp') {
                    bat 'mvn clean package'
                }
            }
        }

        stage('Deploy WAR Manually') {
            steps {
                dir('DeclarativeWebapp') {
                    bat 'echo Current directory: %CD%'
                    bat 'dir target'
                    bat 'if exist "%CATALINA_HOME%\\webapps\\" (echo Path exists) else (echo Path does NOT exist)'
                    bat 'copy target\\DeclarativeWebapp.war "%CATALINA_HOME%\\webapps\\"'
                }
            }
        }

        stage('Start Tomcat (Background)') {
            steps {
                bat 'start "" "%CATALINA_HOME%\\bin\\startup.bat"'
                bat 'ping -n 21 127.0.0.1 > nul'
                bat 'netstat -ano | findstr :8045'
            }
        }
    }
}
