pipeline {
    agent any

    tools {
        maven 'Maven_3.8.6'
        jdk 'JDK_17'
    }

    environment {
        CATALINA_HOME = 'D:\\DevopsTaining\\All softwares\\apache-tomcat-9.0.104\\apache-tomcat-9.0.104'
    }

    stages {
        stage('Build WAR') {
            steps {
                dir('DeclarativeWebapp') {
                    bat 'mvn clean package'
                }
            }
        }

        stage('Deploy WAR Manually') {
            steps {
                dir('DeclarativeWebapp') {
                    bat 'echo Current directory: %CD%'
                    bat 'dir target'
                    bat 'if exist "%CATALINA_HOME%\\webapps\\" (echo Path exists) else (echo Path does NOT exist)'
                    bat 'copy target\\DeclarativeWebapp.war "%CATALINA_HOME%\\webapps\\"'
                }
            }
        }

        stage('Start Tomcat (Foreground)') {
            steps {
                bat '"%CATALINA_HOME%\\bin\\catalina.bat" run'
            }
        }

        // Optional stage if you want Jenkins to wait for Tomcat to fully start
        //stage('Wait for Tomcat') {
            //steps {
               // bat 'timeout /t 15'
           // }
        }
    }
}
